<?php

namespace DoctrineORMModule\Proxy\__CG__\OAuth\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OAuthClient extends \OAuth\Entity\OAuthClient implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getClient_id()
    {
        $this->__load();
        return parent::getClient_id();
    }

    public function getSecret()
    {
        $this->__load();
        return parent::getSecret();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getRedirect_url()
    {
        $this->__load();
        return parent::getRedirect_url();
    }

    public function getAuto_approve()
    {
        $this->__load();
        return parent::getAuto_approve();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setClient_id($client_id)
    {
        $this->__load();
        return parent::setClient_id($client_id);
    }

    public function setSecret($secret)
    {
        $this->__load();
        return parent::setSecret($secret);
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setRedirect_url($redirect_url)
    {
        $this->__load();
        return parent::setRedirect_url($redirect_url);
    }

    public function setAuto_approve($auto_approve)
    {
        $this->__load();
        return parent::setAuto_approve($auto_approve);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'client_id', 'secret', 'name', 'redirect_url', 'auto_approve');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}