<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TimeLine extends \Application\Entity\TimeLine implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function getDeadline()
    {
        $this->__load();
        return parent::getDeadline();
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function setContent($content)
    {
        $this->__load();
        return parent::setContent($content);
    }

    public function setDeadline($deadline)
    {
        $this->__load();
        return parent::setDeadline($deadline);
    }

    public function setImages($images)
    {
        $this->__load();
        return parent::setImages($images);
    }

    public function setComments($comments)
    {
        $this->__load();
        return parent::setComments($comments);
    }

    public function getFavorited_users()
    {
        $this->__load();
        return parent::getFavorited_users();
    }

    public function getJoined_users()
    {
        $this->__load();
        return parent::getJoined_users();
    }

    public function setFavorited_users($favorited_users)
    {
        $this->__load();
        return parent::setFavorited_users($favorited_users);
    }

    public function setJoined_users($joined_users)
    {
        $this->__load();
        return parent::setJoined_users($joined_users);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCreate_at()
    {
        $this->__load();
        return parent::getCreate_at();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'content', 'deadline', 'id', 'create_at', 'status', 'images', 'comments', 'favorited_users', 'joined_users', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}