<div id="page" class="fullscreen">

    <div id="home-static-image">
    	<div id="oauth">
            <div id="login">
                <form class="form-signin" method="post" action="" >
                    <p>xxxx"xxxxx;</p>                 
                    <button id="btn-approve" name="approve" type="submit">
                        <span class="inline-block">授权</span>
                    </button>

                    <button id="btn-deny" name="deny" class="color" type="submit">
                        <span class="inline-block">取消</span>
                    </button>
                </form>
            </div>
        </div>
    </div>

</div><!-- #page -->