<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('TA API ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() . '/css/modern.css' ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() . '/css/style.css' ?>">
        <!-- Scripts -->
        <?php echo $this->headScript()
                    ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                    ->prependFile($this->basePath() . '/js/modern/input-control.js')
                    ->prependFile($this->basePath() . '/js/modern/pagecontrol.js')
                    ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body class="metrouicss">
        <div class="page">
            <div class="page-region">
                <div class="page-region-content">

                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>

        <div class="page">
            <hr />
            <footer>
                <p>&copy; 2013 - by billyct <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        

        <?php echo $this->inlineScript() ?>
    </body>
</html>
