<div class="grid">
    <div class="row">
        <div class="span4 offset2">
            <form id="form-signup" class="form" method="post" action="" >
                <div class="input-control text">
                    <input name="username" id="input-username" value="<?php echo $sina_user->getName() ?>" type="text" placeholder="用户名" />
                    <button class="btn-clear"></button>
                </div>

                <div class="input-control text">
                    <input name="email" id="input-email" type="text" placeholder="Email" />
                    <button class="btn-clear"></button>
                </div>

                <div class="input-control password">
                    <input name="password" id="input-password" type="password" placeholder="密码"/>
                    <button class="btn-reveal"></button>
                </div>

                <div class="input-control">
                    <input name="signup" id="btn-signup" type="submit" value="注册"/>
                    <a href="javascript:void(0);" onclick="window.close();">取消</a>
                </div>
            </form>        
        </div>
    </div>
</div>
